const META={RULE:["FIXED RULE","#137a4b","#e9f6ef"],SCOUT:["SCOUT STATE","#205da8","#eaf2fc"],METER:["METER / COUNTER","#205da8","#eaf2fc"],VERIFY:["PHOTO / VERIFY","#a65c00","#fff3de"]};
let tab="route",filter="ALL",query="",selected=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function favs(){try{return new Set(JSON.parse(localStorage.getItem("coushattaFavs")||"[]"))}catch(e){return new Set()}}
function saveFavs(s){localStorage.setItem("coushattaFavs",JSON.stringify([...s]))}
function visible(g){if(tab==="route"&&g.p>12)return false;if(tab==="fav"&&!favs().has(g.p))return false;if(filter!=="ALL"&&g.s!==filter)return false;if(query&&!([g.t,g.m,g.l,g.a,g.n].join(" ").toLowerCase().includes(query)))return false;return true}
function vis(){return G.filter(visible)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function visual(v){let body="",label="";const top='<svg viewBox="0 0 320 160" xmlns="http://www.w3.org/2000/svg"><text x="12" y="14" font-size="9" font-weight="700" fill="#62748a">ILLUSTRATED ADVANTAGE STATE</text>';const end='</svg>';
if(["scarab","golden_egypt","lock_spin","sticky_reels","frames","grid","prize_blocks"].includes(v)){for(let r=0;r<3;r++)for(let c=0;c<5;c++){let x=18+c*58,y=28+r*34,hot=(c+r)%3===0;body+=`<rect x="${x}" y="${y}" width="48" height="25" rx="6" fill="${hot?"#fff1b8":"#fff"}" stroke="${hot?"#c7982e":"#d8e2ec"}" stroke-width="2"/>`;}label=v==="scarab"?"Gold frames on reels 1–3":v==="golden_egypt"?"Stored coin holders":"Persistent loaded positions + counter";}
else if(["multiplier","reel_multiplier"].includes(v)){body='<rect x="58" y="35" width="204" height="80" rx="14" fill="#fff" stroke="#d8e2ec" stroke-width="2"/><text x="160" y="85" text-anchor="middle" font-size="44" font-weight="800" fill="#c7982e">5x</text>';label="Stored multiplier";}
else if(v==="reel_heights"){[[55,5],[82,6],[110,7]].forEach((z,i)=>{let[h,rows]=z,x=28+i*94,y=122-h;body+=`<rect x="${x}" y="${y}" width="66" height="${h}" rx="8" fill="#fff" stroke="#d8e2ec" stroke-width="2"/><text x="${x+33}" y="${y+h/2+5}" text-anchor="middle" font-size="14" font-weight="800" fill="#205da8">${rows} rows</text>`});label="Reels grow toward 7 rows";}
else if(["counter","meter","progressive","mhb5","gems","three_meters","wolf_meters"].includes(v)){[[92,"#205da8"],[87,"#137a4b"],[81,"#a23b3b"]].forEach((z,i)=>{let[p,c]=z,y=34+i*34;body+=`<rect x="30" y="${y}" width="260" height="22" rx="8" fill="#fff" stroke="#d8e2ec"/><rect x="30" y="${y}" width="${2.6*p}" height="22" rx="8" fill="${c}" opacity=".24"/><text x="42" y="${y+15}" font-size="10" font-weight="700" fill="#10243e">${p}%</text>`});label="Read actual meter / counter / ceiling";}
else if(v==="lanterns"){body='<text x="30" y="50" font-size="18" font-weight="800" fill="#205da8">BLUE 36 / 40</text><text x="30" y="82" font-size="18" font-weight="800" fill="#137a4b">GREEN 55 / 60</text><text x="30" y="114" font-size="18" font-weight="800" fill="#a23b3b">RED 92 / 100</text>';label="Use lantern numbers, not pig animation";}
else if(["pigs","piggy"].includes(v)){[["BLUE 22","#205da8"],["YELLOW","#c7982e"],["RED","#a23b3b"]].forEach((z,i)=>{let[t,c]=z,cx=70+i*90;body+=`<circle cx="${cx}" cy="78" r="30" fill="${c}"/><text x="${cx}" y="82" text-anchor="middle" font-size="10" font-weight="800" fill="#fff">${t}</text>`});label="Persistent pig / bank state";}
else if(["bubbles","ocean","spheres"].includes(v)){[[60,74,23,"$5"],[130,52,18,"$2"],[205,84,27,"$10"],[270,55,16,"$1"]].forEach(z=>{let[x,y,r,t]=z;body+=`<circle cx="${x}" cy="${y}" r="${r}" fill="#eaf2fc" stroke="#205da8" stroke-width="2"/><text x="${x}" y="${y+4}" text-anchor="middle" font-size="10" font-weight="700" fill="#205da8">${t}</text>`});label="Persistent object value + position";}
else{body='<rect x="60" y="35" width="200" height="80" rx="14" fill="#fff" stroke="#d8e2ec" stroke-width="2"/><text x="160" y="81" text-anchor="middle" font-size="28" font-weight="800" fill="#a65c00">PHOTO</text>';label="Full screen + meters + wager panel";}
return top+body+`<text x="160" y="148" text-anchor="middle" font-size="11" font-weight="700" fill="#10243e">${label}</text>`+end}
function render(){let V=vis();$("#vc").textContent=V.length;$("#empty").classList.toggle("show",!V.length);$("#routeBox").classList.toggle("show",tab==="route");
if(!V.length){$("#gameSelect").innerHTML="";$("#quick").innerHTML="";$("#card").innerHTML="";return}
if(!selected||!V.some(g=>g.p===selected))selected=V[0].p;
$("#gameSelect").innerHTML=V.map(g=>`<option value="${g.p}" ${g.p===selected?"selected":""}>${String(g.p).padStart(2,"0")} · ${esc(g.t)}</option>`).join("");
$("#quick").innerHTML=V.slice(0,12).map(g=>`<button data-p="${g.p}"><b>${String(g.p).padStart(2,"0")}</b> · ${esc(g.t)}</button>`).join("");
let g=V.find(x=>x.p===selected),[lab,col,bg]=META[g.s],F=favs(),isf=F.has(g.p),maps=g.maps.map(([n,s])=>`<a class="map" target="_blank" rel="noopener" href="https://www.coushattacasinoresort.com/slot-map.php?sid=${s}">📍 ${esc(n)} · SID ${s}</a>`).join("");
$("#card").innerHTML=`<article class="card"><div class="head"><div class="num">#${String(g.p).padStart(2,"0")}</div><div class="hmain"><div class="title">${esc(g.t)}</div><div class="maker">${esc(g.m)}</div><span class="badge" style="color:${col};background:${bg}">${lab}</span></div><button class="fav ${isf?"on":""}" id="favBtn">${isf?"★":"☆"}</button></div><div class="body"><div class="visual">${visual(g.v)}</div><div class="vnote">Recognition guide: compare this to the cabinet, then read the actual counters/meters before wagering.</div><div class="box"><div class="lab">LOOK FOR</div>${esc(g.l)}</div><div class="box" style="background:${bg};border-color:${col}"><div class="lab">ACTION RULE</div><b>${esc(g.a)}</b></div><div class="box warn"><div class="lab">DO NOT MISREAD</div>${esc(g.n)}</div><div class="box"><div class="lab">COUSHATTA MAP</div><div class="mapgrid">${maps}</div></div></div></article>`;
$("#favBtn").onclick=()=>{let s=favs();s.has(g.p)?s.delete(g.p):s.add(g.p);saveFavs(s);render()};$("#quick").querySelectorAll("button").forEach(b=>b.onclick=()=>{selected=+b.dataset.p;render();window.scrollTo({top:0,behavior:"smooth"})})}
$("#tabs").onclick=e=>{let b=e.target.closest("button[data-tab]");if(!b)return;tab=b.dataset.tab;$$('.tabs .pillbtn').forEach(x=>x.classList.toggle("on",x===b));selected=null;render()};
$("#filters").onclick=e=>{let b=e.target.closest("button[data-f]");if(!b)return;filter=b.dataset.f;$$('.filters .pillbtn').forEach(x=>x.classList.toggle("on",x===b));selected=null;render()};
$("#q").oninput=e=>{query=e.target.value.trim().toLowerCase();selected=null;render()};$("#gameSelect").onchange=e=>{selected=+e.target.value;render()};render();