window.G = [
  {
    p: 1,
    t: "Scarab",
    m: "IGT",
    s: "RULE",
    v: "scarab",
    l: "10-spin cycle. Gold-framed positions persist until spin 10; framed spots then become wild.",
    a: "After spins 1-4: look for 2+ gold frames on reels 1-3. After spins 5-9: look for 3+ gold frames on reels 1-3.",
    n: "Do not value old results. The inherited gold frames and cycle position are what matter.",
    maps: [["1¢ map", 1783], ["2¢ map", 1784]]
  },
  {
    p: 2,
    t: "Golden Egypt",
    m: "IGT",
    s: "RULE",
    v: "golden_egypt",
    l: "Each reel has two stored coin positions. Two coins turn that reel wild for the next two paid spins.",
    a: "Strong public screening rule: at least 1 stored coin on TWO of reels 1, 2 and 3. Active wild reels are stronger.",
    n: "Coins only on reels 4-5 are much weaker. Check every denomination/bet because states can differ.",
    maps: [["1¢ map", 1777], ["2¢ map", 1778]]
  },
  {
    p: 3,
    t: "Dancing Drums: Golden Drums",
    m: "Light & Wonder",
    s: "RULE",
    v: "multiplier",
    l: "Stored multiplier above reel 1. The useful state is the displayed 2x-8x multiplier, not a full-looking bowl.",
    a: "2x-3x: skip. 4x: published playable floor. 5x+: stronger. 8x: strongest visible stored state.",
    n: "Do not apply this rule to regular Dancing Drums or other Dancing Drums Link titles.",
    maps: [["Golden Drums map", 1072]]
  },
  {
    p: 4,
    t: "Ultra Rush Gold Family",
    m: "Incredible Technologies",
    s: "SCOUT",
    v: "lock_spin",
    l: "Gold Lock Spins. Locked gold scatters persist; another scatter refreshes that reel/state counter.",
    a: "Best scout: 5 locked gold scatters with spins remaining. 4 locked with 2-3 spins remaining is also worth close inspection.",
    n: "Do not chase a fresh or lightly loaded state. Exact EV depends on locked count, positions and spins remaining.",
    maps: [["African Adventure", 724], ["Midnight Ice", 728], ["Mythical Phoenix", 653], ["Tiger Run", 603]]
  },
  {
    p: 5,
    t: "Grand Buddha Link / Grand Cat Link",
    m: "IGT",
    s: "SCOUT",
    v: "reel_multiplier",
    l: "Persistent reel multipliers with an 8-spin window. Left-side 5x/6x/8x multipliers are especially valuable.",
    a: "Look for multiple high multipliers on the left with 4-6 spins remaining. More multipliers + more spins = stronger state.",
    n: "A lone 3x with one spin remaining is weak. Check the actual remaining-spin counter.",
    maps: [["Grand Buddha", 621], ["Grand Cat", 622]]
  },
  {
    p: 6,
    t: "Cash Falls: Pirate's Trove",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "sticky_reels",
    l: "Sticky cash/coin symbols remain on individual reels for a limited number of spins; new coins can refresh that reel.",
    a: "Look for nearly full reels, meaningful coin values and 2-3 spins remaining. Multiple loaded reels are especially attractive.",
    n: "One low-value coin with one spin left is not enough. Exact value depends on the whole layout.",
    maps: [["Pirate's Trove map", 1856]]
  },
  {
    p: 7,
    t: "Cash Wizard: Magic Trio",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "sticky_reels",
    l: "Persistent cash-symbol/reel progress closely related to the Cash Falls style of inherited state.",
    a: "Favor heavily loaded reels with useful counters remaining. Send a full-screen photo for borderline states.",
    n: "Do not play only because the screen looks busy; the number, value and remaining life of stored symbols matter.",
    maps: [["Magic Trio map", 414]]
  },
  {
    p: 8,
    t: "Buffalo Ascension",
    m: "Aristocrat",
    s: "SCOUT",
    v: "reel_heights",
    l: "Reels 2-4 can grow from 4 rows toward 7 rows and remain enlarged until the corresponding feature resets.",
    a: "6-7 high reels are the states to investigate. A 7-row reel is the strongest visible build state.",
    n: "4/4/4 is fresh. A single reel at 5 is usually not a reason by itself to play.",
    maps: [["Buffalo Ascension", 683]]
  },
  {
    p: 9,
    t: "Buffalo Link",
    m: "Aristocrat",
    s: "METER",
    v: "counter",
    l: "Persistent Buffalo free-feature counter, stored separately across denomination/bet combinations.",
    a: "Scout all bet/denomination combinations and look for the counter unusually close to its ~1,800 ceiling.",
    n: "Do not infer anything from recent wins or losses. The visible counter is the relevant inherited variable.",
    maps: [["Buffalo Link 1¢", 1752], ["2¢", 1753], ["5¢", 1754], ["10¢", 1755], ["25¢", 1756]]
  },
  {
    p: 10,
    t: "Phoenix Link Family",
    m: "Aristocrat",
    s: "METER",
    v: "counter",
    l: "Persistent Phoenix feature counter. Public references place the forced-trigger ceiling near 1,888.",
    a: "Check every denomination/bet. The closer the counter is to 1,888, the more inherited value it may carry.",
    n: "Artwork and jackpot size alone are not the AP signal. Use the counter.",
    maps: [["Confucius Say", 1343], ["General Tso", 1350], ["Queen Chiu", 1357], ["Sensei Master", 1364]]
  },
  {
    p: 11,
    t: "Zhao Cai Zhu: Yo Ho Hog / Gettin' Piggy With It",
    m: "IGT",
    s: "RULE",
    v: "lanterns",
    l: "Three must-hit-by lantern meters. Blue 10→40, Green 15→60, Red 25→100.",
    a: "Higher toward each ceiling is better. Multiple meters simultaneously near their ceilings are strongest.",
    n: "Ignore the large gold pig/treasure animation. The blue, green and red meter numbers are what matter.",
    maps: [["Get Piggy With It", 995], ["Yo Ho Hog", 996]]
  },
  {
    p: 12,
    t: "Rich Little Piggies: Hog Wild / Meal Ticket",
    m: "Light & Wonder",
    s: "RULE",
    v: "pigs",
    l: "Three persistent pigs. Blue is the free-spin build; the other pigs enhance jackpot/reel behavior.",
    a: "Public screening rule: Blue pig 18+ is playable territory; 25+ is a more conservative/stronger entry.",
    n: "Very high variance. Make sure the displayed state belongs to the same wager/bet level you plan to use.",
    maps: [["Hog Wild", 1628], ["Meal Ticket", 1627]]
  },
  {
    p: 13,
    t: "Bubble Mania: Potion Pays",
    m: "AGS",
    s: "VERIFY",
    v: "bubbles",
    l: "Persistent bubbles move upward through the display. Bubble value and position both matter.",
    a: "More valuable bubbles in useful positions create the inherited edge. Photograph the whole state before playing.",
    n: "Do not use bubble count alone; low-value bubbles near expiration can be weak.",
    maps: [["Potion Pays", 859]]
  },
  {
    p: 14,
    t: "Captain Riches",
    m: "AGS",
    s: "VERIFY",
    v: "coins",
    l: "Persistent coin progress above reels 2-4. Three coins can convert a reel into a temporary wild reel; multiplier coins matter.",
    a: "Active multiplied wild reels or several nearly completed reels are the states worth inspecting.",
    n: "Two ordinary coins can still be a trap. Ignore decorative treasure animations.",
    maps: [["Captain Riches", 1635]]
  },
  {
    p: 15,
    t: "Coin Catch Cove",
    m: "Incredible Technologies*",
    s: "VERIFY",
    v: "coin_counters",
    l: "Persistent coin/reel countdown state. Multiple live reels with meaningful stored values are stronger.",
    a: "Photograph the full cabinet screen and all counters before playing; evaluate the complete state.",
    n: "Do not play a lone weak counter merely because it is non-zero. *Inventory/catalog manufacturer data should be visually confirmed.",
    maps: [["Coin Catch Cove", 1013]]
  },
  {
    p: 16,
    t: "Dragon Sphere Free Games",
    m: "IGT",
    s: "VERIFY",
    v: "spheres",
    l: "Persistent sphere positions/values move through the screen and can differ by wager level.",
    a: "More valuable spheres in favorable positions create the state. Check every bet level and photograph loaded screens.",
    n: "Do not assume all visible spheres have equal value; position and type matter.",
    maps: [["1¢", 657], ["2¢", 658], ["5¢", 659]]
  },
  {
    p: 17,
    t: "Fu Dai Lian Lian BOOST: Peacock / Tiger",
    m: "Aristocrat",
    s: "VERIFY",
    v: "boost",
    l: "BOOST-specific persistent indicators. These versions are distinct from ordinary Fu Dai Lian Lian bag animations.",
    a: "Inspect the actual BOOST state at each wager level; photograph an advanced BOOST display before wagering.",
    n: "Do not use this rule on non-BOOST Dragon/Panda versions simply because a bag looks full.",
    maps: [["BOOST Peacock", 1740], ["BOOST Tiger", 1744]]
  },
  {
    p: 18,
    t: "Ocean Magic",
    m: "IGT",
    s: "VERIFY",
    v: "ocean",
    l: "Persistent wild bubbles move through the reels. Count and location are both important.",
    a: "Several useful bubbles in favorable positions are stronger. Photograph the full reel layout.",
    n: "Do not use a simple bubble-count rule; where the bubbles are matters.",
    maps: [["1¢", 451], ["2¢", 452], ["5¢", 453]]
  },
  {
    p: 19,
    t: "Ocean Magic: Bubble Boost",
    m: "IGT",
    s: "VERIFY",
    v: "ocean",
    l: "Related persistent bubble engine, but the Bubble Boost variant can store state differently by mode/bet.",
    a: "Check all bet levels and the exact bubble layout. Photograph before playing.",
    n: "Do not automatically apply classic Ocean Magic thresholds to Bubble Boost.",
    maps: [["Bubble Boost", 929]]
  },
  {
    p: 20,
    t: "Prize Pool: Fierce Dragon",
    m: "Incredible Technologies",
    s: "VERIFY",
    v: "prize_blocks",
    l: "Persistent colored credit blocks correspond to reel positions and can enhance Prize Pool outcomes.",
    a: "High-value block configurations are the state to inspect. Photograph the full block layout and bet panel.",
    n: "There is no reliable public one-number entry rule for this exact configuration.",
    maps: [["Fierce Dragon", 819]]
  },
  {
    p: 21,
    t: "Temple Falls: Jungle Adventure",
    m: "Incredible Technologies",
    s: "VERIFY",
    v: "grid",
    l: "Persistent prize/coin grid. A heavily developed grid carries more inherited value than a mostly empty one.",
    a: "Photograph advanced grids with substantial stored values before playing.",
    n: "Do not chase a mildly filled board; this is a high-variance state game.",
    maps: [["Temple Falls", 919]]
  },
  {
    p: 22,
    t: "Magic Treasures Gold: Emperor / Empress",
    m: "IGT",
    s: "VERIFY",
    v: "treasure",
    l: "Persistent money-ball/treasure progress. Coushatta's database spells these 'Magiic Treasures Gold.'",
    a: "Large accumulated money-ball states are the ones to inspect. Photograph the complete state.",
    n: "Do not estimate from theme artwork alone.",
    maps: [["Gold Emperor", 1680], ["Gold Empress", 1681]]
  },
  {
    p: 23,
    t: "Huff N Puff: We've Had Enuff",
    m: "Light & Wonder",
    s: "VERIFY",
    v: "frames",
    l: "Persistent frame-building mechanic. Frame count, upgrades and remaining-spin state matter.",
    a: "Advanced/upgraded frame boards can be strong; photograph the full board and counters.",
    n: "Do not apply this mechanic to every Huff & Puff title at Coushatta.",
    maps: [["We've Had Enuff", 1376]]
  },
  {
    p: 24,
    t: "Pay Upgrade: Lightning Wilds",
    m: "Everi",
    s: "SCOUT",
    v: "pay_upgrade",
    l: "A Pay Upgrade on reel 3 doubles eligible 7/bar wins for the next three spins.",
    a: "If a machine is abandoned with Pay Upgrade spins visibly remaining, that is inherited value worth inspecting.",
    n: "Do not chase the feature from a fresh state just because the game supports it.",
    maps: [["Lightning Wilds", 1132]]
  },
  {
    p: 25,
    t: "Ascending Fortunes: Pagoda Rise / Jewel Oasis",
    m: "Incredible Technologies",
    s: "METER",
    v: "mhb5",
    l: "Five must-hit-style meters. Public ranges: Mega 250-350, Grand 200-250, Major 150-200, Minor 100-150, Mini 75-125.",
    a: "Several meters simultaneously deep into their ranges are much stronger than one mildly elevated meter.",
    n: "Do not use one universal entry number; evaluate the full meter combination.",
    maps: [["Pagoda Rise", 918], ["Jewel Oasis", 936]]
  },
  {
    p: 26,
    t: "Stack Up Pays Family",
    m: "Incredible Technologies",
    s: "METER",
    v: "mhb5",
    l: "Five-meter framework similar to Ascending Fortunes; each meter contributes to the state.",
    a: "Scout for several meters simultaneously near the top of their displayed ranges.",
    n: "One meter that only looks 'high' is not enough without the other meter values.",
    maps: [["Island Riches", 254], ["Sakura Riches", 255], ["Double Island Riches", 1463]]
  },
  {
    p: 27,
    t: "Regal Link: Lion / Raven",
    m: "IGT",
    s: "METER",
    v: "gems",
    l: "Multiple persistent gem/meter values. Higher meters and multiple advanced meters increase inherited value.",
    a: "Conservative public scouting: meters roughly 80%+ toward their displayed ceilings, especially multiple at once.",
    n: "Check each bet level. Do not treat a single moderately high gem as an automatic play.",
    maps: [["Regal Link Lion", 2619], ["Regal Link Raven", 2620]]
  },
  {
    p: 28,
    t: "River Dragons",
    m: "AGS",
    s: "METER",
    v: "meter",
    l: "Progressive/must-hit meter state. Current meter, reset and displayed ceiling are the variables that matter.",
    a: "Photograph the current meter and any must-hit-by language/ceiling before deciding.",
    n: "A large progressive number alone is not enough without knowing reset and hit-by conditions.",
    maps: [["River Dragons", 89]]
  },
  {
    p: 29,
    t: "Buffalo Instant Hit",
    m: "Aristocrat",
    s: "VERIFY",
    v: "progressive",
    l: "The AP component is primarily the stand-alone Grand/Major progressive values, not a persistent buffalo collection screen.",
    a: "High values above reset can add meaningful EV. Photograph the Grand/Major values and bet requirement.",
    n: "Do not assume a progressive is +EV merely because it has grown.",
    maps: [["Buffalo Instant Hit", 697]]
  },
  {
    p: 30,
    t: "Fire Light Eruption",
    m: "Aristocrat",
    s: "VERIFY",
    v: "three_meters",
    l: "Three persistent colored meters (blue, green, red). The combination matters, not simply the highest single meter.",
    a: "An elevated green meter with supporting red/blue state can be more attractive than blue alone. Photograph all three.",
    n: "Do not blindly chase Blue at 99; public AP references specifically warn that this can be a trap.",
    maps: [["Fire Light Eruption", 748]]
  },
  {
    p: 31,
    t: "Lock It Link: Piggy Bankin'",
    m: "Light & Wonder",
    s: "VERIFY",
    v: "piggy",
    l: "Persistent pig/bank progress toward a feature. Fewer remaining steps generally means more inherited value.",
    a: "Photograph an advanced pig/bank state and the wager panel before playing.",
    n: "Exact entry depends on the version and wager; there is no safe universal visual threshold.",
    maps: [["Piggy Bankin'", 1559]]
  },
  {
    p: 32,
    t: "Jackpot Catcher",
    m: "Aristocrat",
    s: "VERIFY",
    v: "generic",
    l: "Recognized AP-capable title, but the exact Coushatta configuration needs state-specific verification.",
    a: "Photograph every visible progress meter, persistent symbol and bet requirement before wagering.",
    n: "Do not use a vague 'looks close' rule.",
    maps: [["Jackpot Catcher", 8]]
  },
  {
    p: 33,
    t: "Luckymon Evolution: All That Glitter / Silver Platter",
    m: "Light & Wonder",
    s: "VERIFY",
    v: "generic",
    l: "Current AP catalogs identify the family, but public analysis does not provide a dependable one-number entry rule.",
    a: "Photograph the entire persistent display, counters and wager panel.",
    n: "Treat as identify-and-verify, not automatic advantage play.",
    maps: [["All That Glitter", 979], ["Silver Platter", 980]]
  },
  {
    p: 34,
    t: "Sizzlin' 7's Piggy Parade",
    m: "IGT",
    s: "VERIFY",
    v: "piggy",
    l: "Persistent pig/progress display recognized by current AP catalogs.",
    a: "Photograph the pig/progress state and wager requirement before playing.",
    n: "No trustworthy public numerical entry threshold is available for this exact Coushatta configuration.",
    maps: [["Piggy Parade", 1211]]
  },
  {
    p: 35,
    t: "Wolf Run Eclipse",
    m: "IGT",
    s: "VERIFY",
    v: "wolf_meters",
    l: "Multiple persistent free-game/progressive meters. Combined meter state is the important variable.",
    a: "Photograph all meters and any displayed hit-by language. Strong multiple-meter states deserve evaluation.",
    n: "High variance; do not chase one high-looking number in isolation.",
    maps: [["Wolf Run Eclipse", 928]]
  },
  {
    p: 36,
    t: "Buffalo Diamond Extreme",
    m: "Aristocrat",
    s: "VERIFY",
    v: "generic",
    l: "AP-capable title in current catalogs, but the Extreme version should not inherit rules from other Buffalo Diamond versions without verification.",
    a: "Photograph the full state, progress indicators and bet panel before wagering.",
    n: "Do not apply ordinary Buffalo Diamond thresholds automatically.",
    maps: [["Buffalo Diamond Extreme", 257]]
  },
  {
    p: 37,
    t: "Buffalo Cash",
    m: "Aristocrat",
    s: "METER",
    v: "counter",
    l: "Buffalo Collect Must-Hit-By counter. Collected Buffalo symbols advance a persistent count; the free feature must trigger before 1,800 collected Buffalo.",
    a: "Check the stored counter before betting. Higher toward 1,800 is stronger; very high counters deserve priority. Exact +EV entry still depends on wager and configuration.",
    n: "Do not use recent wins, losses, or Buffalo artwork as the signal. The stored Buffalo Collect counter is the inherited state.",
    maps: [["Buffalo Cash", 2436]]
  },
  {
    p: 38,
    t: "Dragon Unleashed: Three Legends",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "orbs",
    l: "Prize orbs/pearls on reels 1-4 persist by shifting down one row on paid spins. The Dragon Respin can lock orb reels and respin them.",
    a: "Favor multiple higher-value orbs in useful positions with remaining travel. Photograph heavily loaded states; the exact entry threshold is layout-specific.",
    n: "Do not count orbs alone. Orb value, row position, remaining life and wager level all matter.",
    maps: [["Three Legends", 765]]
  },
  {
    p: 39,
    t: "Duo Fu Duo Cai Grand: Dragons",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "moving_wilds",
    l: "Red and Gold Wilds persist at the same bet level and move up one row on each base-game wager until they leave the reel.",
    a: "Multiple wilds with several upward moves remaining are the strongest inherited screens. Lower-position wilds generally have more remaining life than top-row wilds.",
    n: "Do not switch bet level after finding a state. Do not use Ingotcha's sticky-wild rule on Dragons.",
    maps: [["Grand Dragons", 411]]
  },
  {
    p: 40,
    t: "Duo Fu Duo Cai Grand: Ingotcha",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "sticky_wilds",
    l: "Wilds remain fixed for two spins. Landing another Wild refreshes the persistent Wild counter back to two; six sticky Wilds trigger Hold & Re-Spin.",
    a: "Multiple active sticky Wilds with two spins remaining are strongest. Five active Wilds is an especially important near-trigger state to inspect; exact +EV depends on layout and bet.",
    n: "Ingotcha Wilds stay in place. Do not confuse this with Dragons, where persistent Wilds move upward.",
    maps: [["Grand Ingotcha", 412]]
  },
  {
    p: 41,
    t: "Lightning 10 Year Storm",
    m: "Aristocrat",
    s: "METER",
    v: "counter",
    l: "Lightning balls feed a persistent Lightning Free must-hit-by meter. Aristocrat confirms the meter can trigger the free Hold & Spin and may reset to a higher value after the Lightning Free feature.",
    a: "Read the cabinet's actual must-hit-by meter before betting. Higher/closer to its printed ceiling is stronger. Exact +EV entry is not publicly verified, so photograph high states for a precise decision.",
    n: "Do not assume Phoenix Link's 1,888 ceiling. Use this cabinet's own displayed meter, ceiling and wager state.",
    maps: [["Gold Archer", 404], ["Wild Cougar", 405], ["Master Magician", 1460], ["Shang Jin Warrior", 1461]]
  },
  {
    p: 42,
    t: "Legend of the 3x2x Phoenix",
    m: "IGT",
    s: "VERIFY",
    v: "progressive",
    l: "Coushatta lists this as a progressive/free-bonus title and AP references flag the title, but a dependable public inherited-state entry rule has not been verified.",
    a: "Photograph the progressive/free-game display, any persistent counters, and the required wager before playing.",
    n: "Do not infer an advantage from the progressive amount alone.",
    maps: [["3x2x Phoenix", 935]]
  },
  {
    p: 43,
    t: "Raise the Sails",
    m: "IGT",
    s: "METER",
    v: "three_meters",
    l: "Three persistent free-game progression meters—Bronze, Silver and Gold—advance from matching colored coin symbols. A Collect on reel 5 can trigger the matching tier.",
    a: "Higher meter states carry more stored progress. Prioritize machines with one or more clearly advanced meters; photograph borderline states because exact entry thresholds are not public.",
    n: "These are progression meters, not evidence the base game is due. Check that the displayed state belongs to the wager you will use.",
    maps: [["Raise the Sails", 924]]
  },
  {
    p: 44,
    t: "Surefire Frenzy Link: Abundance / Splendor",
    m: "IGT",
    s: "METER",
    v: "many_meters",
    l: "Linked-bank game with 27 must-hit-by progressive meters. Each displayed jackpot has its own current amount and printed ceiling.",
    a: "Scan every displayed meter. Multiple jackpots simultaneously close to their must-hit-by ceilings are the strongest screens; exact +EV depends on hit rates and wager.",
    n: "Do not play because one meter merely looks large. Compare current values with the actual printed hit-by ceilings.",
    maps: [["Abundance", 1037], ["Splendor", 1038]]
  },
  {
    p: 45,
    t: "Ultimate Fire Link: Cash Falls",
    m: "Light & Wonder",
    s: "SCOUT",
    v: "cash_falls",
    l: "On verified Cash Falls variants, Fireballs can stick on a reel for the next three spins. A new Fireball on that reel refreshes its counter to three.",
    a: "Look for reels already loaded with valuable Fireballs and 2-3 spins remaining; multiple loaded or nearly full reels are strongest. Photograph the complete layout for an exact decision.",
    n: "Only apply this to verified Cash Falls variants. Do not assume every Ultimate Fire Link title at Coushatta uses this persistent mechanic.",
    maps: [["China Street 1¢", 1436], ["Olvera Street 1¢", 1441], ["By The Bay", 1816], ["China Street $5", 1300]]
  },
  {
    p: 46,
    t: "Master Da Dang Jia: Fine Fortune / Vivid Diamonds",
    m: "Light & Wonder",
    s: "METER",
    v: "multiplier",
    l: "The persistent Master Multiplier in the center wheel can build up to 18x and carries forward until the feature uses it.",
    a: "Higher stored multipliers are stronger; states approaching the upper end of the 18x range deserve priority. Exact +EV entry is configuration and wager dependent.",
    n: "Use the displayed Master Multiplier, not the apparent fullness of decorative coin graphics.",
    maps: [["Fine Fortune", 920], ["Vivid Diamonds", 921]]
  },
  {
    p: 47,
    t: "Wu Wang Zhe Free Games",
    m: "IGT",
    s: "RULE",
    v: "tokens",
    l: "Five character token meters. After three matching Treasure Tokens for a character, that character becomes a scatter-pay for the next three spins; red is the highest-value character.",
    a: "If active scatter-pay spins remain, play that inherited state at the same wager. Two of three tokens on a high-value character is a strong candidate for closer inspection.",
    n: "Token progress can differ by denomination and bet. Red/blue progress is more valuable than progress on lower-paying characters.",
    maps: [["1¢", 660], ["2¢", 661], ["5¢", 662]]
  },
  {
    p: 48,
    t: "Ocean Magic Treasure Box: Dizzy / Mermaid",
    m: "IGT",
    s: "VERIFY",
    v: "ocean_treasure",
    l: "Dizzy and Mermaid are current Treasure Box variants identified in AP catalogs, but their exact public persistence/entry rule has not been verified as equivalent to classic Ocean Magic.",
    a: "Photograph the full Treasure Box state, reels, meters and wager panel before playing.",
    n: "Do not apply classic Ocean Magic or Bubble Boost rules automatically to Treasure Box.",
    maps: [["Dizzy", 1041], ["Mermaid", 1042]]
  },
  {
    p: 49,
    t: "Wonder 4 Collection / Family",
    m: "Aristocrat",
    s: "VERIFY",
    v: "wonder4",
    l: "Wonder 4 cabinets combine several base games. Any AP value comes from the persistent mechanic of a specific underlying game, not from the Wonder 4 cabinet by itself.",
    a: "Identify the exact Wonder 4 variant and selectable base games first. Only play when an included game shows a verified inherited state.",
    n: "Do not treat every Wonder 4 cabinet, or all four game windows, as automatic AP opportunities.",
    maps: [["Boost", 1481], ["Boost Gold", 474], ["Jackpots", 895], ["Spinning Fortunes", 1563], ["Tall Fortunes", 1483], ["Tower", 1482], ["Revolution", 256], ["Buffalo Wonder 4", 416]]
  },
  {
    p: 50,
    t: "Super Push: Firebird Festival",
    m: "Incredible Technologies",
    s: "VERIFY",
    v: "pusher",
    l: "Coin-pusher-style tray state with coins and special tokens plus a Super Push bonus. Current AP catalogs flag the title, but free public sources do not provide a dependable +EV tray threshold.",
    a: "Photograph the entire tray, special tokens, prize meter and wager requirement before playing.",
    n: "A tray that merely looks full is not enough to prove an advantage. Treat this as photo/verify.",
    maps: [["Firebird Festival", 1638]]
  },
  {
    p: 51,
    t: "Triple Treasure Pots: Eternal Prosperity / Heavenly Wealth",
    m: "Aruze",
    s: "VERIFY",
    v: "pots",
    l: "Three collection pots—Tiger, Dragon and Ox—feed different bonuses. Public manufacturer coverage describes the presentation as perceived persistence.",
    a: "Do not wager from pot fullness alone. Photograph the three pots, any numeric counters and the bet panel so the actual inherited state can be verified.",
    n: "Visual pot growth may be presentation rather than stored player equity; this remains a verify-first title.",
    maps: [["Eternal Prosperity", 985], ["Heavenly Wealth", 986]]
  },
  {
    p: 52,
    t: "Wild Pirates Free Games",
    m: "IGT",
    s: "SCOUT",
    v: "bombs",
    l: "Bomb sub-symbols persist and collect. A lit-fuse bomb starts a countdown that can ignite adjacent stored bombs into Wilds; the feature uses the accumulated bomb pattern.",
    a: "Dense connected bomb clusters plus a favorable active fuse/countdown are the states to inspect. Photograph the board before wagering because the exact +EV threshold is pattern-specific.",
    n: "Do not count bombs without considering adjacency, fuse position/countdown and wager level.",
    maps: [["1¢", 663], ["2¢", 664], ["5¢", 665]]
  }
];
